# Generated by Django 5.0.6 on 2024-06-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAntecedentesMedicos',
            fields=[
                ('id_tipo_antecedentes', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='antecedentesmedicos',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='antecedentesmedicos',
            name='antecedentes_familiares',
        ),
        migrations.RemoveField(
            model_name='antecedentesmedicos',
            name='antecedentes_personales',
        ),
        migrations.RemoveField(
            model_name='antecedentesmedicos',
            name='enfermedades',
        ),
        migrations.AddField(
            model_name='antecedentesmedicos',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='antecedentesmedicos',
            name='tipo_antecedentes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.tipoantecedentesmedicos'),
        ),
    ]
