# Generated by Django 5.0.6 on 2024-06-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_tipoantecedentesmedicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasExamen',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganosSistemas',
            fields=[
                ('id_organos', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_arterial_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='fecha_visita',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='notas_medico',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2011-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='diagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.diagnostico'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.receta'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.tratamiento'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField()),
                ('motivo', models.TextField()),
                ('notas_medicas', models.TextField(default='')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.paciente')),
                ('signos_vitales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.signosvitales')),
            ],
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.consulta'),
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.consulta')),
                ('tipo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.areasexamen')),
            ],
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='examen_fisico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.examenfisico'),
        ),
        migrations.CreateModel(
            name='RevisionOrganosSistemas',
            fields=[
                ('id_revision', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.consulta')),
                ('tipo_organos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.organossistemas')),
            ],
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='organos_sistemas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.revisionorganossistemas'),
        ),
    ]
