# Generated by Django 5.0.6 on 2024-06-10 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_areasexamen_organossistemas_signosvitales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.consulta'),
        ),
        migrations.AlterField(
            model_name='revisionorganossistemas',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.consulta'),
        ),
    ]
