# Generated by Django 5.0.6 on 2024-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
