# Generated by Django 5.0.6 on 2024-06-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_signosvitales_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.consulta'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.diagnostico'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.receta'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='signos_vitales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.signosvitales'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.tratamiento'),
        ),
    ]
