# Generated by Django 3.2.25 on 2024-06-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_examenfisico_historial_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesmedicos',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='notas_medicas',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medicamentos_recetados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='dosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
