# Generated by Django 3.2.25 on 2024-06-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20240613_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
