# Generated by Django 3.2.25 on 2024-06-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_consulta_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_receta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
