# Generated by Django 3.2.25 on 2024-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20240613_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
