# Generated by Django 3.2.25 on 2024-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20240709_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
