# Generated by Django 3.2.25 on 2024-07-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenfisico',
            name='url_examen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionorganossistemas',
            name='url_revision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
